{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"BALANCE_SHEET\",\"PROFIT_AND_LOSS\",\"GENERAL_LEDGER\",\"EXPENSES_SALES_ENHANCED\",\"ACCOUNT\",\"CLASS\",\"BALANCE_PAYROLL\",\"AR_CALCULATIONS\",\"CALCULATIONS\",\"BS_INTUIT_ACCOUNT_GROUPING\",\"BS_CN_ACCOUNT_GROUPING\",\"P&L_ACCOUNT_GROUPING\",\"Staff_FTE\",\"Sheet_Entry_Hour_Lookup\",\"Valid_Date\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Sheet_Entry_Hour_Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"cn-apps2\\cnapps2\", \"CSP_7952_CooperCS\"),",
          "    dbo_Sheet_Entry_View = Source{[Schema=\"dbo\",Item=\"Sheet_Entry_View\"]}[Data],",
          "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_Sheet_Entry_View,{\"staff_KEY\", \"sheet_date\", \"activity__activity_method_KEY\", \"units\", \"amount\"}),",
          "    #\"Filtered to Time Only\" = Table.SelectRows(#\"Removed Other Columns\", each ([activity__activity_method_KEY] = 1)),",
          "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Filtered to Time Only\", \"start_of_month\", each Date.StartOfMonth(Date.From([sheet_date])), type date),",
          "    #\"Grouped Rows\" = Table.Group(#\"Inserted Start of Month\", {\"staff_KEY\", \"start_of_month\"}, {{\"units\", each List.Sum([units]), type nullable number}, {\"amount\", each List.Sum([amount]), type nullable number}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "4a3f9b77-34b6-4d01-aa6b-a8a5be716db1",
        "queryGroup": "FTE_Calculations"
      },
      {
        "name": "Valid_Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"cn-apps2\\cnapps2\", \"CSP_7952_CooperCS\"),",
          "    dbo_Valid_Date = Source{[Schema=\"dbo\",Item=\"Valid_Date\"]}[Data],",
          "    #\"Created Start of Month\" = Table.AddColumn(dbo_Valid_Date, \"start_of_month\", each Date.StartOfMonth(Date.From([valid_date])), type date),",
          "    // This is because 2014 was the first year the firm was using PCS",
          "    #\"After 2013\" = Table.SelectRows(#\"Created Start of Month\", each [start_of_month] >= #date(2014, 1, 1)),",
          "    // the dates must be less than or equal to the year of the current fiscal year.",
          "    #\"Fiscal Year Filter\" = Table.SelectRows(#\"After 2013\", each Date.Year([start_of_month]) <= (if Date.Month(DateTime.LocalNow()) >= 7 then Date.Year(DateTime.LocalNow()) + 1 else Date.Year(DateTime.LocalNow()))),",
          "    // This column checks if the day of the week is between 1 and 5 and - if yes - then place a 1 in the row",
          "    #\"[weekday]\" = Table.AddColumn(#\"Fiscal Year Filter\", \"weekday\", each if Date.DayOfWeek([valid_date]) <= 5 then 1 else null, Int64.Type),",
          "    #\"Grouped by Month\" = Table.Group(#\"[weekday]\", {\"start_of_month\"}, {{\"weekdays\", each List.Sum([weekday]), type number}}),",
          "    // this column will be used to create a cartesian product in the staff table.  The result will be a list of all staff matched with every month from this table",
          "    #\"Added quick_link\" = Table.AddColumn(#\"Grouped by Month\", \"quick_link\", each \"link\", type text)",
          "in",
          "    #\"Added quick_link\""
        ],
        "kind": "m",
        "lineageTag": "371df083-fadf-4df6-8a64-3981cb1eab81",
        "queryGroup": "FTE_Calculations"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "description": "Tables from the regular Cooper Norman QBO database for lookup purposes.",
        "folder": "Lookup_Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Tables created from the FiveTran Transformations steps before they are sent to the snowflake warehouse.",
        "folder": "FiveTran_Transformations"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "description": "Tables from online Excel spreadsheets that dictate where accounts are grouped together.",
        "folder": "Grouping_Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "FTE_Calculations"
      }
    ],
    "relationships": [
      {
        "name": "63e5ce4b-8589-42ea-8681-9d33c006a6b4",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "BALANCE_SHEET",
        "toColumn": "Account_ID",
        "toTable": "BS_INTUIT_ACCOUNT_GROUPING"
      },
      {
        "name": "e293675f-9a67-45f9-9edc-6e4100343cef",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "BALANCE_SHEET",
        "toColumn": "Account_ID",
        "toTable": "BS_CN_ACCOUNT_GROUPING"
      },
      {
        "name": "dee51210-7a41-4b6c-a45b-c07a6fb51b67",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "PROFIT_AND_LOSS",
        "toColumn": "Account_ID",
        "toTable": "P&L_ACCOUNT_GROUPING"
      },
      {
        "name": "66493a8d-1390-4add-9537-0dddbe5d3aef",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "PROFIT_AND_LOSS",
        "toColumn": "ID",
        "toTable": "ACCOUNT"
      },
      {
        "name": "5c3f9718-91ed-4b96-b98b-f14147eeb82a",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "BALANCE_SHEET",
        "toColumn": "ID",
        "toTable": "ACCOUNT"
      },
      {
        "name": "df2bcf20-f2c5-4e88-bc19-fece7453f684",
        "fromColumn": "CLASS_ID",
        "fromTable": "PROFIT_AND_LOSS",
        "toColumn": "ID",
        "toTable": "CLASS"
      },
      {
        "name": "1437cd01-45bb-4864-9b60-28fe7bcedf7c",
        "fromColumn": "CLASS_ID",
        "fromTable": "BALANCE_SHEET",
        "toColumn": "ID",
        "toTable": "CLASS"
      },
      {
        "name": "7a416c06-032d-4423-8741-d440e3aa920f",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "GENERAL_LEDGER",
        "toColumn": "ID",
        "toTable": "ACCOUNT"
      },
      {
        "name": "bef357ad-ae8d-4c44-8298-5220af0bf3dd",
        "fromColumn": "TRANSACTION_LOOKUP_ID",
        "fromTable": "GENERAL_LEDGER",
        "toColumn": "TRANSACTION_LOOKUP_ID",
        "toTable": "EXPENSES_SALES_ENHANCED"
      },
      {
        "name": "80978bc0-7647-4f15-9639-6247d4d7a49f",
        "fromColumn": "Date",
        "fromTable": "_Dates",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c00e84bc-aee6-4cc9-9e80-837e77084e7a"
      },
      {
        "name": "f14ef259-db19-4c77-94c3-25b54692ccce",
        "fromColumn": "CALENDAR_DATE",
        "fromTable": "BALANCE_SHEET",
        "toColumn": "Date",
        "toTable": "_Dates"
      },
      {
        "name": "51c81fd3-3d3f-43cd-aa67-48c65ec18c84",
        "fromColumn": "CALENDAR_DATE",
        "fromTable": "PROFIT_AND_LOSS",
        "toColumn": "Date",
        "toTable": "_Dates"
      },
      {
        "name": "f36b5b3f-b3c3-4d77-8610-3c4fe95a85b7",
        "fromColumn": "Start of Month",
        "fromTable": "GENERAL_LEDGER",
        "toColumn": "Date",
        "toTable": "_Dates"
      },
      {
        "name": "d5a9eed4-2c9b-4d51-a078-0af02ac48117",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "BALANCE_PAYROLL",
        "toColumn": "Account_ID",
        "toTable": "BS_INTUIT_ACCOUNT_GROUPING"
      },
      {
        "name": "a346741d-fec7-92b6-78ca-b7c60a52447a",
        "fromColumn": "OLD_START_OF_MONTH",
        "fromTable": "BALANCE_PAYROLL",
        "toColumn": "Date",
        "toTable": "_Dates"
      },
      {
        "name": "e4fdf56a-bf8e-42ed-b096-444e87e38994",
        "fromColumn": "ACCOUNT_ID",
        "fromTable": "AR_CALCULATIONS",
        "toColumn": "Account_ID",
        "toTable": "BS_INTUIT_ACCOUNT_GROUPING"
      },
      {
        "name": "d0cf54a1-0e23-4de6-9ff2-48b42c04e03d",
        "fromColumn": "Start of Month",
        "fromTable": "AR_CALCULATIONS",
        "toColumn": "Date",
        "toTable": "_Dates"
      },
      {
        "name": "ae3b5db2-45b8-441b-891f-cda218542b2e",
        "fromColumn": "start_of_month",
        "fromTable": "Staff_FTE",
        "toColumn": "Date",
        "toTable": "_Dates"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "BALANCE_SHEET",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CALENDAR_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9cbb37cc-c40d-4cf0-aac1-5294bacbebdd",
            "sourceColumn": "CALENDAR_DATE",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_RELATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c0f5711-3496-4c00-85ce-59de7384c04b",
            "sourceColumn": "SOURCE_RELATION",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_CLASS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eef15917-da8e-4aff-8b80-bd1ccac81a59",
            "sourceColumn": "ACCOUNT_CLASS",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2887ef9b-fcf6-479c-9dc4-409b67cbda9b",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "IS_SUB_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1caafbec-b859-488b-9694-2e6e4ebb3f9c",
            "sourceColumn": "IS_SUB_ACCOUNT",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa9cc49a-2a97-4e38-b57b-6666ab0afb4c",
            "sourceColumn": "PARENT_ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7819b997-17f3-43ae-8672-798587babdcc",
            "sourceColumn": "PARENT_ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64075bf3-5f6b-4923-bca4-3e2f6ca9d6c6",
            "sourceColumn": "ACCOUNT_TYPE",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_SUB_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "047b0aef-25b9-4c67-a144-04429abe5fd6",
            "sourceColumn": "ACCOUNT_SUB_TYPE",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "450c6c1c-524e-4ba5-b564-9c8d5d756526",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25012a92-1a08-4d03-ac9f-9aa5136913fd",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4ec78aa-a1aa-4864-8c4d-f4b6aed637f1",
            "sourceColumn": "ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9cb096aa-fecc-48e9-b3ec-21678f00b546",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT_ORDINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9dac841-4adf-491a-82b5-034a250b34af",
            "sourceColumn": "ACCOUNT_ORDINAL",
            "sourceProviderType": "decimal(1, 0)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3c3c8db2-d201-4b83-9f34-a413d24aa084",
        "partitions": [
          {
            "name": "BALANCE_SHEET",
            "mode": "directQuery",
            "queryGroup": "FiveTran_Transformations",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_QUICKBOOKS_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN_QUICKBOOKS\",Kind=\"Schema\"]}[Data],",
                "    QUICKBOOKS__BALANCE_SHEET_Table = QBO_COOPERNORMAN_QUICKBOOKS_Schema{[Name=\"QUICKBOOKS__BALANCE_SHEET\",Kind=\"Table\"]}[Data]",
                "in",
                "    QUICKBOOKS__BALANCE_SHEET_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PROFIT_AND_LOSS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CALENDAR_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4e561c57-8f38-48ae-8753-678cbd996e29",
            "sourceColumn": "CALENDAR_DATE",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_RELATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0331ba5a-3d6c-4a73-ac9c-9809f80f9e57",
            "sourceColumn": "SOURCE_RELATION",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_CLASS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "902ef4bf-53dc-4ea8-978e-b6a89b089ce2",
            "sourceColumn": "ACCOUNT_CLASS",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b16ea99e-b0ed-4307-9e72-6d64d4128e83",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "IS_SUB_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "419c5e92-ae4a-4875-95c7-a5c228858b13",
            "sourceColumn": "IS_SUB_ACCOUNT",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a2cbf5f-cc1d-416a-a3ba-5c746bb1be04",
            "sourceColumn": "PARENT_ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6a09c07-bf20-4ed7-b014-2e6758cbd3c1",
            "sourceColumn": "PARENT_ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e39e8a5-3bde-49f3-a963-32f7c55327df",
            "sourceColumn": "ACCOUNT_TYPE",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_SUB_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2133471-5075-49da-b92d-1e9a6976c5dc",
            "sourceColumn": "ACCOUNT_SUB_TYPE",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49e6aacc-41ab-4bc9-a292-dff79c1efd18",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc8dd6cc-579a-4465-a4e6-1847e692552d",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7c6240f-4394-498c-98e4-cb7b7f622a40",
            "sourceColumn": "ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2b7fbba-30e6-4684-95c3-694628c6320e",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT_ORDINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "024d81c4-1bee-42a5-969e-6ec6a4828336",
            "sourceColumn": "ACCOUNT_ORDINAL",
            "sourceProviderType": "decimal(1, 0)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "372221d1-9643-4317-8dd1-e9894cd5e0ed",
        "partitions": [
          {
            "name": "PROFIT_AND_LOSS",
            "mode": "directQuery",
            "queryGroup": "FiveTran_Transformations",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_QUICKBOOKS_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN_QUICKBOOKS\",Kind=\"Schema\"]}[Data],",
                "    QUICKBOOKS__PROFIT_AND_LOSS_Table = QBO_COOPERNORMAN_QUICKBOOKS_Schema{[Name=\"QUICKBOOKS__PROFIT_AND_LOSS\",Kind=\"Table\"]}[Data]",
                "in",
                "    QUICKBOOKS__PROFIT_AND_LOSS_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GENERAL_LEDGER",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3341f37a-75c9-4058-ba0c-a92a34f41d5e",
            "sourceColumn": "UNIQUE_ID",
            "sourceProviderType": "nvarchar(32)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e16ed4f-47f6-4554-a4f3-8860216c5419",
            "sourceColumn": "TRANSACTION_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_RELATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f519c26-d140-4cbe-a190-6e3672169e81",
            "sourceColumn": "SOURCE_RELATION",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1853ad99-4773-4725-bffb-0fb9b920b1c5",
            "sourceColumn": "TRANSACTION_INDEX",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "TRANSACTION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f99a7856-49f1-4f69-a358-2237f01ecfa2",
            "sourceColumn": "TRANSACTION_DATE",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTOMER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ac644c2-7b43-4700-822c-914253dc091a",
            "sourceColumn": "CUSTOMER_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81c36adc-c71b-45f0-8bd2-54c9c9c2aee5",
            "sourceColumn": "VENDOR_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f3f7573-1f77-458e-8c83-408d6bad6d05",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d43e4f0-62d6-4380-89de-346d3171d7b1",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a379766e-3815-4e8f-8695-f137cb72368f",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49966863-dcca-48c0-915f-9b8454579399",
            "sourceColumn": "DEPARTMENT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "634c3c9b-2733-4c31-b7c1-fd3022aaded0",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de5dda1-9a8e-4523-8410-d99765c234ea",
            "sourceColumn": "ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "IS_SUB_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f2e48d93-d45f-43dc-81ac-ca23e81b5e21",
            "sourceColumn": "IS_SUB_ACCOUNT",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c14818b7-da60-4196-bf43-50216ea700c0",
            "sourceColumn": "PARENT_ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf25e40d-3131-4f41-b5e9-08ada8d02214",
            "sourceColumn": "PARENT_ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "121bc0ef-4b8c-49a6-9e0c-2452d85034fa",
            "sourceColumn": "ACCOUNT_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_SUB_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e18d735d-2177-4628-be97-d7845f97e655",
            "sourceColumn": "ACCOUNT_SUB_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "FINANCIAL_STATEMENT_HELPER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "121a4da9-1e10-49fe-a046-6955f1b36ac8",
            "sourceColumn": "FINANCIAL_STATEMENT_HELPER",
            "sourceProviderType": "nvarchar(16)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_CURRENT_BALANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "33d7d795-bbb7-4fb0-a07c-185364197fe1",
            "sourceColumn": "ACCOUNT_CURRENT_BALANCE",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT_CLASS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f8f3d9d-f1a9-4eb5-946f-c082effa916b",
            "sourceColumn": "ACCOUNT_CLASS",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25b7583a-a5fb-40a0-8e54-1406516b41fa",
            "sourceColumn": "TRANSACTION_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9f53434-c89d-4299-b8bb-8a437fb30c63",
            "sourceColumn": "TRANSACTION_SOURCE",
            "sourceProviderType": "nvarchar(13)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_TRANSACTION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19a37cf7-0f0f-43d5-a9e8-81f241ff6dba",
            "sourceColumn": "ACCOUNT_TRANSACTION_TYPE",
            "sourceProviderType": "nvarchar(6)",
            "summarizeBy": "none"
          },
          {
            "name": "ADJUSTED_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43a58556-5f75-4a3b-ad84-e3e97603da42",
            "sourceColumn": "ADJUSTED_AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "RUNNING_BALANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d54aff84-78bc-46c7-807b-a381846fb5fd",
            "sourceColumn": "RUNNING_BALANCE",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "ed335377-cfa8-4ae4-a8b3-209107af59f9",
            "sourceColumn": "Start of Month",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_LOOKUP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db8e6158-cb56-4ed9-b51b-e1b902663270",
            "sourceColumn": "TRANSACTION_LOOKUP_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d47c6077-dec1-4bb1-b997-5e568e6031de",
        "partitions": [
          {
            "name": "GENERAL_LEDGER",
            "mode": "directQuery",
            "queryGroup": "FiveTran_Transformations",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_QUICKBOOKS_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN_QUICKBOOKS\",Kind=\"Schema\"]}[Data],",
                "    QUICKBOOKS__GENERAL_LEDGER_Table = QBO_COOPERNORMAN_QUICKBOOKS_Schema{[Name=\"QUICKBOOKS__GENERAL_LEDGER\",Kind=\"Table\"]}[Data],",
                "    #\"Inserted Start of Month\" = Table.AddColumn(QUICKBOOKS__GENERAL_LEDGER_Table, \"Start of Month\", each Date.StartOfMonth([TRANSACTION_DATE]), type date),",
                "    // This column is meant to connect to the Expenses_sales_enhanced column to get the description for the individual journal entries.",
                "    #\"Added TRANSACTION_LOOKUP_ID\" = Table.AddColumn(#\"Inserted Start of Month\", \"TRANSACTION_LOOKUP_ID\", each Text.From([TRANSACTION_ID]) & \"_\" & Text.From([TRANSACTION_INDEX]))",
                "in",
                "    #\"Added TRANSACTION_LOOKUP_ID\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EXPENSES_SALES_ENHANCED",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TRANSACTION_SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00a1c52d-e7a6-4e81-a07f-3dd6b71b8b8a",
            "sourceColumn": "TRANSACTION_SOURCE",
            "sourceProviderType": "nvarchar(7)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4970e18c-315a-4288-aa26-db9482a8900a",
            "sourceColumn": "TRANSACTION_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_RELATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff8490aa-f02d-40e6-89f0-b30b374ce2ba",
            "sourceColumn": "SOURCE_RELATION",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_LINE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d48806c7-b2b4-4927-b3c3-a48ac51e84cd",
            "sourceColumn": "TRANSACTION_LINE_ID",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "none"
          },
          {
            "name": "DOC_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5e30a25-abfa-4f79-b70c-f232cda6cb10",
            "sourceColumn": "DOC_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2435d731-0d2f-4122-ba0d-bc30073cf472",
            "sourceColumn": "TRANSACTION_TYPE",
            "sourceProviderType": "nvarchar(13)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ca53f544-5238-40f6-b969-9620f5fa5ea0",
            "sourceColumn": "TRANSACTION_DATE",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f905a42-4f9d-49ff-acdf-c6d8336699cc",
            "sourceColumn": "ITEM_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_QUANTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "de086b66-6c0f-47ba-96df-38d4a22ff032",
            "sourceColumn": "ITEM_QUANTITY",
            "sourceProviderType": "decimal(28, 6)",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_UNIT_PRICE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2c76756-5855-4a86-85fe-8aab452473d9",
            "sourceColumn": "ITEM_UNIT_PRICE",
            "sourceProviderType": "decimal(28, 6)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88b91936-147d-4517-bd99-87f56630bff7",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "095bfdcd-01b9-439e-b241-44e8b4dbaf5d",
            "sourceColumn": "ACCOUNT_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_SUB_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fabdc34-a8af-497b-8a55-9d5980337d77",
            "sourceColumn": "ACCOUNT_SUB_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7949a00f-e9dd-4189-8f35-2274edc49166",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e86340bd-704b-4eb0-9e67-74ee19bf89ec",
            "sourceColumn": "DEPARTMENT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "319a7b03-acad-4fcd-8be0-78dfc0c0a78e",
            "sourceColumn": "DEPARTMENT_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTOMER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6462378-5997-4cd5-b0af-0083a4da5ebe",
            "sourceColumn": "CUSTOMER_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTOMER_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cee8f397-4ea5-4c04-b3d0-6ce264476e30",
            "sourceColumn": "CUSTOMER_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTOMER_WEBSITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bcfecc6-1d6a-47c6-9978-bd48d206b652",
            "sourceColumn": "CUSTOMER_WEBSITE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb2bb89-eec5-406a-b68b-2440104a2628",
            "sourceColumn": "VENDOR_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8c9e51b-1c85-4347-b84f-cdc0bb1cf657",
            "sourceColumn": "VENDOR_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "BILLABLE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fce7319a-0bcb-4b72-b5cc-7b69e9e8a0ca",
            "sourceColumn": "BILLABLE_STATUS",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "287313b8-f031-4932-a759-e1e4a05d2371",
            "sourceColumn": "DESCRIPTION",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa5c752a-bf03-4ccf-87f4-bb928efd2881",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "604ece49-2bf6-4b58-b8c5-d32b3200c440",
            "sourceColumn": "TOTAL_AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_LOOKUP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a2f0384-d8ba-429e-8070-2e171d50e6fb",
            "sourceColumn": "TRANSACTION_LOOKUP_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "61c95084-a03e-49ef-ac35-435c03d51977",
        "partitions": [
          {
            "name": "EXPENSES_SALES_ENHANCED",
            "mode": "directQuery",
            "queryGroup": "FiveTran_Transformations",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_QUICKBOOKS_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN_QUICKBOOKS\",Kind=\"Schema\"]}[Data],",
                "    QUICKBOOKS__EXPENSES_SALES_ENHANCED_Table = QBO_COOPERNORMAN_QUICKBOOKS_Schema{[Name=\"QUICKBOOKS__EXPENSES_SALES_ENHANCED\",Kind=\"Table\"]}[Data],",
                "    // This column is meant to connect to the General_Ledger table to get the description for the individual journal entries.",
                "    #\"Added TRANSACTION_LINE_ID\" = Table.AddColumn(QUICKBOOKS__EXPENSES_SALES_ENHANCED_Table, \"TRANSACTION_LOOKUP_ID\", each Text.From([TRANSACTION_ID]) & \"_\" & Text.From([TRANSACTION_LINE_ID]))",
                "in",
                "    #\"Added TRANSACTION_LINE_ID\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ACCOUNT",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "b26f1500-ef72-4e29-90b6-8f814b76737f",
            "sourceColumn": "ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07a902fd-7d46-40e1-af6b-bf36644d183d",
            "sourceColumn": "CURRENCY_ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27a493ac-5ced-4640-90c4-007551917c50",
            "sourceColumn": "DESCRIPTION",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "FULLY_QUALIFIED_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0af6bd0-fd92-4d1c-aef9-48f38b623162",
            "sourceColumn": "FULLY_QUALIFIED_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47616a10-05cb-48f6-a345-6ac7818d2324",
            "sourceColumn": "ACCOUNT_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bad698b-1474-407b-9527-8c87595bd1c0",
            "sourceColumn": "NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACTIVE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d033a439-a636-4eaa-994b-6bec3ab5330a",
            "sourceColumn": "ACTIVE",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "CLASSIFICATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15c170e8-629f-4dd0-832b-960ced8375e9",
            "sourceColumn": "CLASSIFICATION",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "SUB_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b88dd7e3-902d-4369-b01e-95ef22e8619c",
            "sourceColumn": "SUB_ACCOUNT",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_SUB_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95cb440a-6a95-4a4a-b4cf-c74a18488042",
            "sourceColumn": "ACCOUNT_SUB_TYPE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "SYNC_TOKEN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "098faa1c-0633-4574-ad0e-5f4bc1d5d71a",
            "sourceColumn": "SYNC_TOKEN",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_AT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0ab4141f-e9eb-4b61-899e-94b6fb7d88e6",
            "sourceColumn": "CREATED_AT",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATED_AT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "feb46be6-574a-44f6-8d2f-faebe5c06bf4",
            "sourceColumn": "UPDATED_AT",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "_FIVETRAN_DELETED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b59a3847-d359-4be4-8b1f-2b12baaea9fd",
            "sourceColumn": "_FIVETRAN_DELETED",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "BALANCE_WITH_SUB_ACCOUNTS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f87872f0-f6dc-4944-9423-3bae10617979",
            "sourceColumn": "BALANCE_WITH_SUB_ACCOUNTS",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "BALANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94eaf40c-51e7-4324-bf8f-0bc1c42ee13d",
            "sourceColumn": "BALANCE",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e56dc5b-4b7a-4d28-8941-3bb39e3c4aba",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4891c8cf-9d5e-4dd8-bb8e-58f5935eb742",
            "sourceColumn": "PARENT_ACCOUNT_ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "TAX_CODE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "084d304b-4e71-429a-a1e5-050c904d66c1",
            "sourceColumn": "TAX_CODE_ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "_FIVETRAN_SYNCED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "93b78d66-bb23-4465-ba4c-99604a728424",
            "sourceColumn": "_FIVETRAN_SYNCED",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          }
        ],
        "description": "Connection to Accounts",
        "lineageTag": "85ad9569-8319-418f-9b1d-5a6cfa5d38cf",
        "partitions": [
          {
            "name": "ACCOUNT",
            "mode": "directQuery",
            "queryGroup": "Lookup_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN\",Kind=\"Schema\"]}[Data],",
                "    ACCOUNT_Table = QBO_COOPERNORMAN_Schema{[Name=\"ACCOUNT\",Kind=\"Table\"]}[Data]",
                "in",
                "    ACCOUNT_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CLASS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "237e6851-ea33-45a8-b3f1-62399730dea9",
            "sourceColumn": "ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "SUB_CLASS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "61a07470-d701-44f4-81a2-32c28a90dfa2",
            "sourceColumn": "SUB_CLASS",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "SYNC_TOKEN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b6fe9f-a661-41e3-8889-9f3eb75e47f8",
            "sourceColumn": "SYNC_TOKEN",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "FULLY_QUALIFIED_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45b8bca2-b8a9-4492-aa48-cd9eb0fd9579",
            "sourceColumn": "FULLY_QUALIFIED_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d3b68e4-0bda-42e6-af27-4229b9c4ab5f",
            "sourceColumn": "NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ACTIVE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4a034d65-0d12-434d-8adb-c703faa59a0b",
            "sourceColumn": "ACTIVE",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_AT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b276ee1c-97b3-4f83-8025-9e48add52194",
            "sourceColumn": "CREATED_AT",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATED_AT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d205d8c1-12e6-489f-be15-5f87d81aa5e0",
            "sourceColumn": "UPDATED_AT",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "_FIVETRAN_DELETED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b33cb7c4-0bb3-4262-bf3d-815056efb937",
            "sourceColumn": "_FIVETRAN_DELETED",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7e0c493-1382-43f3-b15b-a3fb6c4e17f3",
            "sourceColumn": "PARENT_CLASS_ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "_FIVETRAN_SYNCED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e52c0926-2a62-4fe1-837a-541cc9466115",
            "sourceColumn": "_FIVETRAN_SYNCED",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          }
        ],
        "description": "Connections to Classes",
        "lineageTag": "a1986c0c-1aea-41d5-ba76-ec10ae0f8a67",
        "partitions": [
          {
            "name": "CLASS",
            "mode": "directQuery",
            "queryGroup": "Lookup_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN\",Kind=\"Schema\"]}[Data],",
                "    CLASS_Table = QBO_COOPERNORMAN_Schema{[Name=\"CLASS\",Kind=\"Table\"]}[Data]",
                "in",
                "    CLASS_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BALANCE_PAYROLL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_ROW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "a674a6de-9230-4c00-9e0e-729d2ed40b9c",
            "sourceColumn": "_ROW",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a3b8ded-8dfc-4a19-8f22-c23b520fe691",
            "sourceColumn": "ACCOUNT",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_MODIFIED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83aeba77-6637-498c-b415-c57de2d66e7e",
            "sourceColumn": "LAST_MODIFIED_BY",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "ADJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1c95ea5-d4bd-45fb-9403-0fbde9c290c5",
            "sourceColumn": "ADJ",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_MODIFIED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "558c448b-eb5b-4261-8b5f-66c82657dcf0",
            "sourceColumn": "LAST_MODIFIED",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d34ff8-06f2-4b22-b9af-dc3e078f2396",
            "sourceColumn": "SOURCE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "OLD_CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ed90752-55c8-4528-8ac2-4ccd571213a5",
            "sourceColumn": "OLD_CLASS_ID",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "count"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc7b60e8-b1e9-418d-9655-4705cc214d43",
            "sourceColumn": "DESCRIPTION",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "022c7895-c031-43bb-a471-be0c59a34610",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "DOCUMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80f94dcd-1a40-401f-b0dd-e97a4d5d8a96",
            "sourceColumn": "DOCUMENT",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTOMER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f115f228-6dbc-44ed-87e6-0984fbe24b87",
            "sourceColumn": "CUSTOMER",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "OLD_ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02b7b6af-229a-4ba2-b17a-fd2984bfc18d",
            "sourceColumn": "OLD_ACCOUNT_NUMBER",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "ENTITY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d79fd180-f524-4491-bcbc-f9595375bf2e",
            "sourceColumn": "ENTITY_NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7dc7383b-31ab-4178-bad8-628958008781",
            "sourceColumn": "CREATED_BY",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "OLD_TRANSACTION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3805384e-a071-4117-8961-26298f9dc5df",
            "sourceColumn": "OLD_TRANSACTION_DATE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ad18e40-79b4-4b58-8527-2624474d0179",
            "sourceColumn": "NAME",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "BALANCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a4618833-7a6d-453e-8701-93c155c4f3ca",
            "sourceColumn": "BALANCE",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "CREATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f4fa868-e673-430b-ad0e-b567ae8a3ca1",
            "sourceColumn": "CREATE_DATE",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "SPLIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f24368a1-a989-4269-a019-dd31a68884b4",
            "sourceColumn": "SPLIT",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "_FIVETRAN_SYNCED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b5d8072d-1ae5-49f8-828f-4ed1e26ce2fb",
            "sourceColumn": "_FIVETRAN_SYNCED",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "4af2139a-1383-4b84-87a7-2b875660e069",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "50aaf444-70c5-4798-a3ba-0c876127f6d7",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "TRANSACTION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "fbc75fd4-31af-455f-8886-3b69bd185ba3",
            "sourceColumn": "TRANSACTION_DATE",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9fa58d4-d501-4be3-9a63-f62b02ca985a",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "OLD_START_OF_MONTH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adf179eb-aa91-47ab-96c3-e17bcd2e4143",
            "sourceColumn": "OLD_START_OF_MONTH",
            "sourceProviderType": "nvarchar(256)",
            "summarizeBy": "none"
          },
          {
            "name": "START_OF_MONTH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "5b8cc8ec-28e0-4a57-a03f-60101d330826",
            "sourceColumn": "START_OF_MONTH",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          }
        ],
        "description": "The static amount exported from the QBO Payroll system Cooper Norman used to use.  This is not being pulled through by FiveTran.  This table is stored in a Google Sheets file.",
        "lineageTag": "791148c6-e5f8-46bc-83ea-eeb93f3af216",
        "partitions": [
          {
            "name": "BALANCE_PAYROLL",
            "mode": "directQuery",
            "queryGroup": "Lookup_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN\",Kind=\"Schema\"]}[Data],",
                "    BALANCE_PAYROLL_Table = QBO_COOPERNORMAN_Schema{[Name=\"BALANCE_PAYROLL\",Kind=\"Table\"]}[Data],",
                "    // Renaming columns so I can create new columns in the table with the correct types so I can maintain the Direct Query connection",
                "    #\"Renamed Columns\" = Table.RenameColumns(BALANCE_PAYROLL_Table,{{\"CLASS_ID\", \"OLD_CLASS_ID\"}, {\"ACCOUNT_NUMBER\", \"OLD_ACCOUNT_NUMBER\"}, {\"TRANSACTION_DATE\", \"OLD_TRANSACTION_DATE\"}, {\"START_OF_MONTH\", \"OLD_START_OF_MONTH\"}}),",
                "    CLASS_ID = Table.AddColumn(#\"Renamed Columns\", \"CLASS_ID\", each [OLD_CLASS_ID], type text),",
                "    ACCOUNT_NUMBER = Table.AddColumn(CLASS_ID, \"ACCOUNT_NUMBER\", each Text.From([OLD_ACCOUNT_NUMBER]), type text),",
                "    #\"Merged ACCOUNT_ID\" = Table.NestedJoin(ACCOUNT_NUMBER, {\"ACCOUNT_NUMBER\"}, ACCOUNT, {\"ACCOUNT_NUMBER\"}, \"ACCOUNT_TABLE\", JoinKind.LeftOuter),",
                "    ACCOUNT_ID = Table.ExpandTableColumn(#\"Merged ACCOUNT_ID\", \"ACCOUNT_TABLE\", {\"ID\"}, {\"ACCOUNT_ID\"}),",
                "    TRANSACTION_DATE = Table.AddColumn(ACCOUNT_ID, \"TRANSACTION_DATE\", each [OLD_TRANSACTION_DATE], type date),",
                "    START_OF_MONTH = Table.AddColumn(TRANSACTION_DATE, \"START_OF_MONTH\", each [OLD_START_OF_MONTH], type date)",
                "in",
                "    START_OF_MONTH"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CALCULATIONS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "A table meant to house all measures for the report",
        "lineageTag": "c37d5312-984c-4655-b9b1-b5420f74ba3a",
        "measures": [
          {
            "name": "Measure",
            "expression": "\"Test\"",
            "lineageTag": "4bff24df-3497-4107-a1f8-c08a029286b2"
          },
          {
            "name": "Payroll_Balance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR current_month = SELECTEDVALUE(_Dates[Date])",
              "VAR amount = CALCULATE( SUM(BALANCE_PAYROLL[AMOUNT]), USERELATIONSHIP(BS_INTUIT_ACCOUNT_GROUPING[Account_ID], BALANCE_PAYROLL[ACCOUNT_ID]), ALL(_Dates), USERELATIONSHIP(_Dates[Date], BALANCE_PAYROLL[OLD_START_OF_MONTH]), _Dates[Date] <= current_month)",
              "RETURN",
              "",
              "amount"
            ],
            "lineageTag": "26b05621-4b0a-4996-8a84-fddd11ff3936"
          },
          {
            "name": "Balance_Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "SUM(BALANCE_SHEET[AMOUNT])"
            ],
            "lineageTag": "3ea4d008-ead9-4b0c-b6ba-8d42509c29b1"
          },
          {
            "name": "Total_Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[Payroll_Balance] + [Balance_Amount]"
            ],
            "lineageTag": "665d7e86-3467-4c63-aa5f-0254611e1620"
          },
          {
            "name": "AR_Balance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR current_month = SELECTEDVALUE(_Dates[Date])",
              "VAR amount = CALCULATE( SUM(AR_CALCULATIONS[AMOUNT]), USERELATIONSHIP(BS_INTUIT_ACCOUNT_GROUPING[Account_ID], AR_CALCULATIONS[ACCOUNT_ID]), ALL(_Dates), USERELATIONSHIP(_Dates[Date], AR_CALCULATIONS[Start of Month]), _Dates[Date] <= current_month)",
              "RETURN",
              "",
              "amount"
            ],
            "lineageTag": "d788977b-3ffb-47bf-9e69-a3d3c046a400"
          }
        ],
        "partitions": [
          {
            "name": "CALCULATIONS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_0c27b68a-03b1-47c9-b6ed-1be75a5df0a3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ddd91cbf-03c5-4ae7-853b-5d065b73a010",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f047f22a-69b5-4cc6-b8ea-35692cb7a63a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "243c4ddd-573f-40e1-9cc4-557bd7664b66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1c80678c-327b-4df3-8692-d4dd8a7e3e93",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5760906e-9707-46dd-9359-e7a308aa5c05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fd936aea-7f3d-40a2-9d05-80f2e91dd895",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f649b8b5-974b-4caa-88ff-3a74e86df01e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4c28a35c-142f-461a-bf71-4ceb829cb41d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5514b5a8-1224-4706-9862-ec96a23a422c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c414b660-a2bc-402d-b44f-1b3460dadca9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d8cdd34a-55be-4e49-8d7c-a54c8842e611",
                "ordinal": 3
              }
            ],
            "lineageTag": "4d697869-c83c-421b-beec-56892d3e348f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0dc8d98a-5d8a-4926-85f0-643427567926",
        "partitions": [
          {
            "name": "DateTableTemplate_0c27b68a-03b1-47c9-b6ed-1be75a5df0a3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "BS_INTUIT_ACCOUNT_GROUPING",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68ef70b0-84f0-4214-a711-3e104fc87235",
            "sourceColumn": "Account_ID",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 1)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5cac2b9-8830-4e07-9ae7-3d1a450953d0",
            "sourceColumn": "BS (Level 1)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 2)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8197fcc3-b8a1-42f3-a779-2d8bc64ceed9",
            "sourceColumn": "BS (Level 2)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 3)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fc9ce20-d923-4924-bda0-0ecade199286",
            "sourceColumn": "BS (Level 3)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 4)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f4fa39d-1b4e-477f-8c8e-9fb2a127c86b",
            "sourceColumn": "BS (Level 4)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 5)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b2998ba-2a3d-4f99-8896-57cfae2f390d",
            "sourceColumn": "BS (Level 5)",
            "summarizeBy": "none"
          },
          {
            "name": "Sorting (Level 1)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44322c62-7a01-4361-9f36-a6ae03850f66",
            "sourceColumn": "Sorting (Level 1)",
            "summarizeBy": "sum"
          }
        ],
        "description": "Balance sheet accounts grouped how Intuit groups them on balance sheet reports",
        "lineageTag": "236d56d3-158c-438f-a15d-f06985d75401",
        "partitions": [
          {
            "name": "BS_INTUIT_ACCOUNT_GROUPING",
            "mode": "import",
            "queryGroup": "Grouping_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/\", [ApiVersion = 15]),",
                "    #\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\" = Source{[Name=\"QBO_COOPERNORMAN_ACCOUNTS.xlsx\",#\"Folder Path\"=\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/Shared Documents/Data Information/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\"),",
                "    Balance_Default2_Table = #\"Imported Excel Workbook\"{[Item=\"Balance_Default2\",Kind=\"Table\"]}[Data]",
                "in",
                "    Balance_Default2_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BS_CN_ACCOUNT_GROUPING",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25f692a8-01e9-4cbe-a074-45893c8d8a05",
            "sourceColumn": "Account_ID",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 1)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "635dab3f-0212-498c-a07c-9c72365a34a5",
            "sourceColumn": "BS (Level 1)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 2)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92d63d2e-09aa-47b9-a0d9-738ddbfe945f",
            "sourceColumn": "BS (Level 2)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 3)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d52950b-c850-408e-b8e2-946aecd30e30",
            "sourceColumn": "BS (Level 3)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 4)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5522fe4-01a5-45c3-8b59-5080707aae10",
            "sourceColumn": "BS (Level 4)",
            "summarizeBy": "none"
          },
          {
            "name": "BS (Level 5)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1fd6284-295f-4ad3-a698-3240d3b73888",
            "sourceColumn": "BS (Level 5)",
            "summarizeBy": "none"
          }
        ],
        "description": "Balance sheet accounts grouped the way Remington and his team would like to see them.",
        "lineageTag": "b93ef6ac-0ba8-49c0-b2fb-5a190e56dd7e",
        "partitions": [
          {
            "name": "BS_CN_ACCOUNT_GROUPING",
            "mode": "import",
            "queryGroup": "Grouping_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/\", [ApiVersion = 15]),",
                "    #\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\" = Source{[Name=\"QBO_COOPERNORMAN_ACCOUNTS.xlsx\",#\"Folder Path\"=\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/Shared Documents/Data Information/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\"),",
                "    Balance_Table = #\"Imported Excel Workbook\"{[Item=\"Balance\",Kind=\"Table\"]}[Data]",
                "in",
                "    Balance_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "P&L_ACCOUNT_GROUPING",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "302dd3bf-1809-4603-9a22-c048424cba3d",
            "sourceColumn": "Account_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sorting (Level 1)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "836afdde-1f18-481e-991c-95d814d02bb7",
            "sourceColumn": "Sorting (Level 1)",
            "summarizeBy": "none"
          },
          {
            "name": "PNL (Level 0)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66b0be9a-0886-4c12-b726-d6d05244d3ab",
            "sourceColumn": "PNL (Level 0)",
            "summarizeBy": "none"
          },
          {
            "name": "PNL (Level 1)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69228794-1c86-4a10-b45a-6ed18a68340b",
            "sourceColumn": "PNL (Level 1)",
            "summarizeBy": "none"
          },
          {
            "name": "PNL (Level 2)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ef9b042-82a0-4708-966a-7b877687cd53",
            "sourceColumn": "PNL (Level 2)",
            "summarizeBy": "none"
          },
          {
            "name": "PNL (Level 3)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc3bf9e0-7802-4726-80fa-c9fa2a48f003",
            "sourceColumn": "PNL (Level 3)",
            "summarizeBy": "none"
          },
          {
            "name": "PNL (Level 4)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08cb1b26-2ce8-4991-a2ef-996efd8b2475",
            "sourceColumn": "PNL (Level 4)",
            "summarizeBy": "none"
          },
          {
            "name": "Sorting (Level 0)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f97664c9-55a0-4d56-aa34-a0f9a1b2d002",
            "sourceColumn": "Sorting (Level 0)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS.ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fb9bc00-9dd5-42c5-b543-ee599e54def3",
            "sourceColumn": "CLASS.ID",
            "summarizeBy": "none"
          }
        ],
        "description": "Profit and Loss accounts grouped the way Remington and his team would like to see them.",
        "lineageTag": "dfb8fdb7-9529-44b7-81c8-beafee55b8c7",
        "partitions": [
          {
            "name": "P&L_ACCOUNT_GROUPING",
            "mode": "import",
            "queryGroup": "Grouping_Tables",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/\", [ApiVersion = 15]),",
                "    #\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\" = Source{[Name=\"QBO_COOPERNORMAN_ACCOUNTS.xlsx\",#\"Folder Path\"=\"https://coopernorman.sharepoint.com/sites/CN-DataInformation/Shared Documents/Data Information/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"QBO_COOPERNORMAN_ACCOUNTS xlsx_https://coopernorman sharepoint com/sites/CN-DataInformation/Shared Documents/Data Information/\"),",
                "    Accounts_List_Table = #\"Imported Excel Workbook\"{[Item=\"Accounts_List\",Kind=\"Table\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(Accounts_List_Table, {\"PNL (Level 2)\"}, CLASS, {\"NAME\"}, \"CLASS\", JoinKind.LeftOuter),",
                "    // Merged using the PNL (Level 1) column to the Name column in the Class table.  Obtaining the ID for the class will help us to link to that Class' budget for the year.",
                "    #\"Expanded CLASS\" = Table.ExpandTableColumn(#\"Merged Queries\", \"CLASS\", {\"ID\"}, {\"CLASS.ID\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded CLASS\",{{\"Account_ID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Dates",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1b01905cc21440d6939eb0772caad417"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "40d9ea0d-df10-42c5-811e-3b6f1dd4fd09",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c00e84bc-aee6-4cc9-9e80-837e77084e7a"
                },
                "isDefault": true,
                "relationship": "80978bc0-7647-4f15-9639-6247d4d7a49f"
              }
            ]
          },
          {
            "name": "FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR current_month = MONTH([Date])",
              "VAR current_year = YEAR([Date])",
              "VAR fiscal = IF( current_month >= 7, CONCATENATE(\"FY_\", current_year + 1), CONCATENATE(\"FY_\", current_year))",
              "RETURN",
              "",
              "fiscal",
              "// Returns the fiscal year for the selected date."
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a32a6222-231f-4a6e-b689-515257080b2d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF( DAY([Date]) = 1, \"SOM\")",
              "",
              "// Returns the string \"SOM\" if the selected date is the first of the month."
            ],
            "isDataTypeInferred": true,
            "lineageTag": "00a34635-e3d7-499c-bb8d-e544f02a75b1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "640a0cc6-d067-4e72-a8fc-b0e63d96b68d",
        "partitions": [
          {
            "name": "_Dates",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR end_date = ",
                "    IF( MONTH(TODAY()) >= 7, ",
                "        DATE( YEAR(TODAY()) + 1, 7, 1) - 1,",
                "        IF( MONTH( TODAY()) = 6, ",
                "            DATE( YEAR(TODAY()), 8, 1) - 1,",
                "            DATE( YEAR(TODAY()), 7, 1) - 1))",
                "RETURN",
                "",
                "CALENDAR( DATE( 2013, 1, 1), end_date)",
                "",
                "// This table will be dynamic, allowing users to view data from 2013 (the first year PCS and QBO data is available), to the end of the current fiscal year. ",
                "// However, if the current month is June, users will be allowed to view the first month of the following fiscal year."
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c00e84bc-aee6-4cc9-9e80-837e77084e7a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "081bbfc4-535f-4c9e-830a-22b7e671e772",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d3c83cdb-f557-4de8-8ff6-8d7ebe6dd8b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "29312026-b6b1-4cd3-9b1d-7c8a3a74b1c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dfed6b3e-cd54-4098-a070-9e6a06809822",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "34614626-dc0a-4eab-be9b-b4bb250c97e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "03942110-3e6f-4004-aaa0-5e328233a75f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1ce55d79-f86b-4c74-886b-ca8dc3a650de",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "802fe59f-6e90-441c-bde0-b68d5c5dac46",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "62deb8c0-021c-49f2-ba0d-d7e90b07d929",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8e2dbee7-9585-41cc-9520-5ea33cea3b75",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3c20b718-bcd5-458f-b531-0a5f37e67daa",
                "ordinal": 3
              }
            ],
            "lineageTag": "19fcd968-f835-4721-811d-27d5989de54e"
          }
        ],
        "isHidden": true,
        "lineageTag": "d5eecf2f-4c2b-4471-9c68-e8432baf0d23",
        "partitions": [
          {
            "name": "LocalDateTable_c00e84bc-aee6-4cc9-9e80-837e77084e7a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('_Dates'[Date])), 1, 1), Date(Year(MAX('_Dates'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "AR_CALCULATIONS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "a6c7ab1b-e62a-47f1-b04b-3ffcdcba7f04",
            "sourceColumn": "Start of Month",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfb07397-01ce-4544-b94b-dc7cb6dcbdba",
            "sourceColumn": "ACCOUNT_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "ACCOUNT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8be6bbb3-a363-46ad-b8e7-ad20bf731cfe",
            "sourceColumn": "ACCOUNT_NUMBER",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f22f6a3b-7047-4141-b6c6-738c0dfddd5d",
            "sourceColumn": "CLASS_ID",
            "sourceProviderType": "nvarchar(16777216)",
            "summarizeBy": "none"
          },
          {
            "name": "debit_no_payment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9f02711-0f19-4f09-a1d7-b6bbc50cfaeb",
            "sourceColumn": "debit_no_payment",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "credit_no_payment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd22fc89-b722-40fb-a136-72dbcee2678b",
            "sourceColumn": "credit_no_payment",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "03b03d2a-1770-4cc0-9722-49cef4b19ddf",
            "sourceColumn": "AMOUNT",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          }
        ],
        "description": "This table is meant to adjust the accounts receivable amounts by using the amounts found in the ledger table.",
        "lineageTag": "38366f27-d4b7-4e78-ac2d-93e7a9892c30",
        "partitions": [
          {
            "name": "AR_CALCULATIONS",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"nt21881.us-central1.gcp.snowflakecomputing.com\",\"FIVETRAN_WAREHOUSE\"),",
                "    FIVETRAN_DATABASE_Database = Source{[Name=\"FIVETRAN_DATABASE\",Kind=\"Database\"]}[Data],",
                "    QBO_COOPERNORMAN_QUICKBOOKS_Schema = FIVETRAN_DATABASE_Database{[Name=\"QBO_COOPERNORMAN_QUICKBOOKS\",Kind=\"Schema\"]}[Data],",
                "    QUICKBOOKS__GENERAL_LEDGER_Table = QBO_COOPERNORMAN_QUICKBOOKS_Schema{[Name=\"QUICKBOOKS__GENERAL_LEDGER\",Kind=\"Table\"]}[Data],",
                "    #\"Inserted Start of Month\" = Table.AddColumn(QUICKBOOKS__GENERAL_LEDGER_Table, \"Start of Month\", each Date.StartOfMonth([TRANSACTION_DATE]), type date),",
                "    #\"AR Only\" = Table.SelectRows(#\"Inserted Start of Month\", each [ACCOUNT_NUMBER] = \"113\" or [ACCOUNT_NUMBER] = \"120\" or [ACCOUNT_NUMBER] = \"121\"),",
                "    debit_no_payment = Table.AddColumn(#\"AR Only\", \"debit_no_payment\", each if [TRANSACTION_TYPE] = \"debit\" and [TRANSACTION_SOURCE] <> \"payment\" then [AMOUNT] else 0),",
                "    credit_no_payment = Table.AddColumn(debit_no_payment, \"credit_no_payment\", each if [TRANSACTION_TYPE] = \"credit\" and [TRANSACTION_SOURCE] <> \"payment\" then [AMOUNT] else 0),",
                "    #\"Grouped Rows\" = Table.Group(credit_no_payment, {\"Start of Month\", \"ACCOUNT_ID\", \"ACCOUNT_NUMBER\", \"CLASS_ID\"}, {{\"debit_no_payment\", each List.Sum([debit_no_payment]), type nullable number}, {\"credit_no_payment\", each List.Sum([credit_no_payment]), type nullable number}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Grouped Rows\", \"AMOUNT\", each [debit_no_payment] - [credit_no_payment], type number)",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff_FTE",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "staff_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "4c1654c7-028b-4be2-b614-9f03c5aa20c3",
            "sourceColumn": "staff_KEY",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "c3b8fd32-18a9-4672-9ac3-6599e7b95ea8",
            "sourceColumn": "staff_id",
            "sourceProviderType": "nvarchar(11)",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "e9cb3b91-f6c3-4de7-a7f6-a7fe1adde4ed",
            "sourceColumn": "description",
            "sourceProviderType": "nvarchar(250)",
            "summarizeBy": "none"
          },
          {
            "name": "date_hired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d6ae5250-d694-416f-8663-fd001caa056b",
            "sourceColumn": "date_hired",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "date_left",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "55b87751-9fbd-4fcf-ae41-1b5c5907e91d",
            "sourceColumn": "date_left",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "staff_status_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "2b71a769-2a06-4d26-a800-66356003db5c",
            "sourceColumn": "staff_status_KEY",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "staff_level_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a4a11e2-cdb1-4385-9ffb-f3580e6d3179",
            "sourceColumn": "staff_level_id",
            "sourceProviderType": "nvarchar(11)",
            "summarizeBy": "none"
          },
          {
            "name": "department_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96b4c1c0-fb06-434d-9917-889db65439c0",
            "sourceColumn": "department_id",
            "sourceProviderType": "nvarchar(11)",
            "summarizeBy": "none"
          },
          {
            "name": "month_hired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9881dca7-c75e-44a0-af38-2f91ee3414b7",
            "sourceColumn": "month_hired",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "month_left",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a2e09498-df6c-4319-8cac-f4341755886b",
            "sourceColumn": "month_left",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "quick_link",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "54899ab7-9cf9-425b-a7f3-3ff0274a88f5",
            "sourceColumn": "quick_link",
            "sourceProviderType": "varchar(4)",
            "summarizeBy": "none"
          },
          {
            "name": "start_of_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "93b262fb-5a30-4aa6-814a-77ddd54fa73a",
            "sourceColumn": "start_of_month",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bec08b9-b4a6-4741-b6df-e69951ef7e24",
            "sourceColumn": "units",
            "sourceProviderType": "decimal(38, 2)",
            "summarizeBy": "sum"
          },
          {
            "name": "FTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": [
              "",
              "// Determines (as a number) the year from the selected FY.",
              "//    VAR year_chosen = VALUE( RIGHT([FY], 4))",
              "// Determines the number of hours (Full-Time) to be worked in a month.  2080 / 12 to find per month.",
              "    VAR full_time_month = 160",
              "// Determines the max result per month. Full time per year should be capped at 1, so per month it should be represented by 1 / 12.",
              "    VAR max_result = 1 / 12",
              "",
              "// Determines the Start of Month of when the employee was hired.",
              "    VAR month_hired = [month_hired]",
              "// Determines the Start of Month of when the employee left.",
              "    VAR month_left = [month_left]",
              "// Determines the Start of Month for the row selected.",
              "    VAR month_chosen = [start_of_month]",
              "// Determines the Start of Month of today.",
              "    VAR month_today = DATE(YEAR(TODAY()), MONTH(TODAY()), 1)",
              "// Determines the last day of the selected month.",
              "    VAR month_end = DATE(YEAR(month_chosen), MONTH(month_chosen) + 1, 1) - 1",
              "// Finds the number of days in the current month.",
              "    VAR days_num = (month_end - month_chosen) + 1",
              "// Determines what day the selected fiscal year should end on.  If the current fiscal year it should end on today. Used for calculating hours in the selected period.",
              "    VAR hours_year_end = IF( month_chosen = month_today, TODAY(), month_end)",
              "// Finds the number of weekdays in the selected month year. Used to determine if there are more than 2080 workable hours in a year.  If there are more it will be capped at 2080, if there are less the actual workable hours will be used.",
              "    VAR fiscal_weekdays = [Weekdays]",
              "// Finds the number of hours possible in the current month (Weekdays * 8)",
              "    VAR hours_possible = IF( fiscal_weekdays * 8 > full_time_month, full_time_month, fiscal_weekdays * 8)",
              "RETURN",
              "",
              "// Filter out if they weren't working that year",
              "    IF( ISBLANK([Fiscal Days]),",
              "    BLANK(),",
              "    // If they are NOT full time and it is in the current month, divide the number of hours they worked by total hours allowed (weekdays * 8), cap at max_result.",
              "    IF( [fte_level] <> \"1\" && month_chosen = month_today,",
              "        IF( ([units] / hours_possible) * max_result /* Determines the full_time_month */ > max_result, max_result, ([units] / hours_possible) * max_result),",
              "        // Check if the employee is NOT full time and it is not in the current month.  If yes, divide their worked hours by full_time_month.",
              "        IF( [fte_level] <> \"1\" && month_chosen <> month_today, ",
              "            IF( ([units] / full_time_month) * max_result > max_result, max_result, ([units] / full_time_month) * max_result),",
              "            // If they ARE full time but started this month, divide the days since their hire by total days in the month.",
              "            IF( month_hired = month_chosen, ",
              "                ( ( [End of Month] - [date_hired] + 1) / days_num) * max_result, // Determines the percentage of days in the month that the employee worked and then multiplies that by the max result to see what percentage of the max result should be assigned to that month.",
              "                // If they ARE full time but left part way through the month divide the number of days before they left by total days in the month.",
              "                IF( month_left = month_chosen, ",
              "                    ( ( [date_left] - month_chosen + 1) / days_num) * max_result, // Determines the percentage of days in the month that the employee worked and then multiplies that by the max result to see what percentage of the max result should be assigned to that month.",
              "                    // If they are a PARTER or PRINCIPAL then set them to the max result",
              "                    IF( [staff_level_id] in {\"PARTNER\", \"PRINCIPAL\"}, max_result,",
              "                    // If they ARE full time, weren't hired or left this month, but we are calculating for an incomplete month, divide days worked by total days in fiscal year.",
              "                    IF( month_chosen = month_today, ",
              "                        ( [Fiscal Days] / days_num) * max_result,",
              "                        // If FT and a previous month, check to see if hours are greater than 160 and - if not - calculate based on hours.",
              "                            IF( month_chosen <> month_today && [units] < full_time_month, ",
              "                            IF( ([units] / hours_possible) * max_result /* Determines the full_time_month */ > max_result, max_result, ([units] / hours_possible) * max_result),",
              "                            // If this is for a previous month and they worked the whole month as a full-time, then make it the max result.",
              "                            max_result))))))))"
            ],
            "lineageTag": "4cdca503-4af2-4deb-b37f-a53915aeaa6e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "fte_level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fe5783b-614b-4fbf-9757-3322098fad2d",
            "sourceColumn": "fte_level",
            "sourceProviderType": "float",
            "summarizeBy": "none"
          },
          {
            "name": "weekdays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "967d7325-2aff-485c-b6ff-9b2904ad8f6c",
            "sourceColumn": "weekdays",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "69e444ca-ab25-4c46-969d-539aa8de60c0",
        "partitions": [
          {
            "name": "Staff_FTE",
            "mode": "directQuery",
            "queryGroup": "FTE_Calculations",
            "source": {
              "expression": [
                "let",
                "    // Returns the start of the current month for comparisons in FTE calculations",
                "    this_month = Date.From(Date.StartOfMonth(DateTime.LocalNow())),",
                "",
                "    Source = Sql.Database(\"cn-apps2\\cnapps2\", \"CSP_7952_CooperCS\"),",
                "    dbo_Staff = Source{[Schema=\"dbo\",Item=\"Staff\"]}[Data],",
                "    // The date hired and date left columns need to be date instead of datetime",
                "    #\"Change Date Types\" = Table.TransformColumnTypes(dbo_Staff,{{\"date_hired\", type date}, {\"date_left\", type date}}),",
                "    #\"Expanded Staff_Level\" = Table.ExpandRecordColumn(#\"Change Date Types\", \"Staff_Level\", {\"staff_level_id\"}, {\"staff_level_id\"}),",
                "    #\"Expanded Department\" = Table.ExpandRecordColumn(#\"Expanded Staff_Level\", \"Department\", {\"department_id\"}, {\"department_id\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded Department\",{\"staff_KEY\", \"staff_id\", \"description\", \"date_hired\", \"date_left\", \"staff_status_KEY\", \"staff_level_id\", \"department_id\"}),",
                "    // Indicates the level the staff member is for the fte calculation",
                "    #\"[fte_level]\" = Table.AddColumn(#\"Removed Other Columns\", \"fte_level\", each if [staff_level_id] = \"OTHER\" or [department_id] = \"OTHER\" then null else if [staff_level_id] = \"PARTTIME\" or [staff_level_id] = \"INTERN\" or [staff_level_id] = \"TERMINATED\" then 0.5 else 1),",
                "    // changing the month hired column to a start of month to compare to the current month",
                "    #\"[month_hired]\" = Table.AddColumn(#\"[fte_level]\", \"month_hired\", each Date.StartOfMonth(Date.From([date_hired])), type date),",
                "    // Changing the date_left column to a start of month for a comparison to the start of the current month",
                "    #\"[month_left]\" = Table.AddColumn(#\"[month_hired]\", \"month_left\", each Date.StartOfMonth(Date.From([date_left])), type date),",
                "    // this column will be used to create a cartesian product in the staff table.  The result will be a list of all staff matched with every month from this table",
                "    #\"Added quick_link\" = Table.AddColumn(#\"[month_left]\", \"quick_link\", each \"link\", type text),",
                "    // This step will create a cartesian product of the staff table and all start of month values from the valid date table.",
                "    #\"Merged Valid_date\" = Table.NestedJoin(#\"Added quick_link\", {\"quick_link\"}, Valid_Date, {\"quick_link\"}, \"Valid_Date\", JoinKind.LeftOuter),",
                "    #\"Expanded Valid_Date\" = Table.ExpandTableColumn(#\"Merged Valid_date\", \"Valid_Date\", {\"start_of_month\", \"weekdays\"}, {\"start_of_month\", \"weekdays\"}),",
                "    // The sheet entry lookup table is meant to group all time entries from the sheet entry table by start of month and the staff key.  We used those two columns to merge to this table to find the hours the staff member coded in that month.",
                "    #\"Merged Sheet_Entry_Lookup\" = Table.NestedJoin(#\"Expanded Valid_Date\", {\"staff_KEY\", \"start_of_month\"}, Sheet_Entry_Hour_Lookup, {\"staff_KEY\", \"start_of_month\"}, \"units\", JoinKind.LeftOuter),",
                "    #\"Expanded units\" = Table.ExpandTableColumn(#\"Merged Sheet_Entry_Lookup\", \"units\", {\"units\"}, {\"units\"})",
                "in",
                "    #\"Expanded units\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}